<template>
  <div class="loadingio-spinner-spinner-m6fcvhoraja"><div class="ldio-pt4f6b6fqq">
  <div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div>
  </div></div>
</template>

<style type="text/css">
@keyframes ldio-pt4f6b6fqq {
  0% { opacity: 1 }
  100% { opacity: 0 }
}
.ldio-pt4f6b6fqq div {
  left: 90px;
  top: 40px;
  position: absolute;
  animation: ldio-pt4f6b6fqq linear 1s infinite;
  background: #e50914;
  width: 20px;
  height: 20px;
  border-radius: 10px / 10px;
  transform-origin: 10px 60px;
}.ldio-pt4f6b6fqq div:nth-child(1) {
  transform: rotate(0deg);
  animation-delay: -0.9s;
  background: #e50914;
}.ldio-pt4f6b6fqq div:nth-child(2) {
  transform: rotate(36deg);
  animation-delay: -0.8s;
  background: #e50914;
}.ldio-pt4f6b6fqq div:nth-child(3) {
  transform: rotate(72deg);
  animation-delay: -0.7s;
  background: #e50914;
}.ldio-pt4f6b6fqq div:nth-child(4) {
  transform: rotate(108deg);
  animation-delay: -0.6s;
  background: #e50914;
}.ldio-pt4f6b6fqq div:nth-child(5) {
  transform: rotate(144deg);
  animation-delay: -0.5s;
  background: #e50914;
}.ldio-pt4f6b6fqq div:nth-child(6) {
  transform: rotate(180deg);
  animation-delay: -0.4s;
  background: #e50914;
}.ldio-pt4f6b6fqq div:nth-child(7) {
  transform: rotate(216deg);
  animation-delay: -0.3s;
  background: #e50914;
}.ldio-pt4f6b6fqq div:nth-child(8) {
  transform: rotate(252deg);
  animation-delay: -0.2s;
  background: #e50914;
}.ldio-pt4f6b6fqq div:nth-child(9) {
  transform: rotate(288deg);
  animation-delay: -0.1s;
  background: #e50914;
}.ldio-pt4f6b6fqq div:nth-child(10) {
  transform: rotate(324deg);
  animation-delay: 0s;
  background: #e50914;
}
.loadingio-spinner-spinner-m6fcvhoraja {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: rgba(NaN, NaN, NaN, 0);
}
.ldio-pt4f6b6fqq {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-pt4f6b6fqq div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>
